export enum Unit {
  CELSIUS = 'C',
  VOLTAGE = 'V',
  AMPERAGE = 'A',
  AMPHOURS = 'Ah',
  PERCENT = '%',
  HEX = 'HEX',
  BINARY = 'BIN',
  NEWTON_METERS = 'N-m',
  DEGREES = 'deg',
  RPM = 'rpm',
  HERTZ = 'Hz',
  WEBERS = 'Wb',
  SECONDS = 's',
  G = 'g',
  FAHRENHEIT = 'F',
  METERS_PER_SECOND = 'm/s',
  COORD = 'coord',
  STRING = '',
  VOLTS = 'V',
  DBM = 'dBm',
  METERS_PER_SECOND_SQUARED = 'm/s^2',
  PSI = 'psi'
}
