name: Update Submodule and Create Pull Request

on:
  push:
    branches:
      - main # Trigger when changes are pushed to the main branch of the submodule
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
    - name: Checkout Submodule
      uses: actions/checkout@v3
    - name: Create New Branch in Parent Repository
      env:
        PAT: ${{ secrets.PARENT_REPO_PAT }}
        PARENT_REPO_OWNER: Northeastern-Electric-Racing
        PARENT_REPO_NAME: Argos
        NEW_BRANCH_NAME: update-submodules # Replace with your desired branch name
        BASE_BRANCH: main # Replace with the base branch where you want to create the new branch
      run: |
        # Authenticate using your GitHub Personal Access Token
        git config --global user.email "actions@github.com"
        git config --global user.name "GitHub Actions"
        
        # Clone the parent repository
        git clone https://github.com/$PARENT_REPO_OWNER/$PARENT_REPO_NAME.git

        # Navigate into the repository
        cd $PARENT_REPO_NAME

        # Create a new branch from the desired base branch
        git checkout -b $NEW_BRANCH_NAME $BASE_BRANCH

        # Push the new branch to the remote repository
        git push origin $NEW_BRANCH_NAME

    - name: Update Submodule
      run: |
        # Update the submodule in your local repository
        git submodule update --recursive --remote

    - name: Commit Changes in Submodule
      run: |
        # Commit the changes in the submodule
        git add .
        git commit -m "Update submodule commit"
        git push

    - name: Create Pull Request in Parent Repository
      env:
        PAT: ${{ secrets.PARENT_REPO_PAT }}
        PARENT_REPO_OWNER: Northeastern-Electric-Racing
        PARENT_REPO_NAME: Argos
        BASE_BRANCH: main # Replace with the base branch where you want to create the pull request
        HEAD_BRANCH: ${{ github.ref }} # Use the current branch in the submodule as the head branch
      run: |
        # Create a pull request using the GitHub REST API
        response=$(curl -X POST \
          -H "Authorization: token $PAT" \
          -H "Accept: application/vnd.github.v3+json" \
          https://api.github.com/repos/$PARENT_REPO_OWNER/$PARENT_REPO_NAME/pulls \
          -d '{
            "title": "Update Submodules",
            "body": "Updating Submodules",
            "head": "$HEAD_BRANCH",
            "base": "$BASE_BRANCH"
          }')

        # Extract the pull request URL from the response
        pull_request_url=$(echo $response | jq -r .html_url)

        echo "Pull Request URL: $pull_request_url"